
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmanager-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookmanager-api
  template:
    metadata:
      labels:
        app: bookmanager-api
    spec:
      containers:
      - name: bookmanager-api
        image: ${{ secrets.REGISTRY_URL }}/bookmanager-api:latest
        ports:
        - containerPort: 8080
